apiVersion: v1
kind: Service
metadata:
  name: sqlexporter-svc
  labels:
    app: sqlexporter-app
    
spec:
  selector:
    app: sqlexporter
  ports:
    - name: sqlexporter 
      protocol: TCP
      port: 9237
      targetPort: 9237
  type: ClusterIP
